### ISSUE TITLE
coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by ShengkunZhang** [alexfeng/InternationalizationScript-iOS#2]
importLocalizableDemoV2.0中出现下列错误
coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "importLocalizable.py", line 68, in <module>
    main()
  File "importLocalizable.py", line 65, in main
    importLocalizable(options)
  File "importLocalizable.py", line 42, in importLocalizable
    table = data.sheets()[0]
AttributeError: 'NoneType' object has no attribute 'sheets'

**Comment by alexfeng** [comment]
你看看你的xlrd 模块有没有正确安装

**Comment by ShengkunZhang** [comment]
如果没安装好，是不是第一版，也没法跑起来。第一版没问题的

**Comment by alexfeng** [comment]
你能把你使用的文档发给我看下，我怀疑是不是和文档的编码有关系！

**Comment by alexfeng** [comment]
我修改了下代码，你重新拉取跑一下看看

**Comment by RoshanDev** [comment]
加上 `-f` 参数试试，直接跑这个 `python importLocalizableV2.0.py localizableFromExcel.xls` ，我也出了这个问题。加上 `-f` 就偶了。 @ShengkunZhang
